language: csharp
solution: src/VcEngineAutomation.sln

script:
  - msbuild /p:Configuration=Release src/VcEngineAutomation.sln
  - nuget pack ./nuspec/VcEngineAutomation.nuspec

deploy:
  skip_cleanup: true
  provider: script
  script: 
    - nuget push VcEngine.Automation.*.nupkg -ApiKey $NUGET_API_KEY  -Source https://www.nuget.org/api/v2/package 
  on:
    branch: master