language: csharp
solution: src/VcEngineAutomation.sln

env:
  global:
    - PKG_VERSION=0.0.3

before_script:
  - curl -Lsfo build.sh https://cakebuild.net/download/bootstrapper/linux
  - chmod a+x build.sh

script:
  - ./build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: 
    - nuget push output/VcEngine.Automation.*.nupkg -ApiKey $NUGET_API_KEY  -Source https://www.nuget.org/api/v2/package
  on:
    branch: master
