language: csharp
solution: src/VcEngineAutomation.sln

env:
  global:
    - PKG_VERSION=0.3.9

script:
  - ./build.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - ./build.sh --target=NugetPush --nugetKey=$NUGET_API_KEY
    on:
      tags: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: output/VcEngineRunner.$PKG_VERSION.zip
    on:
      tags: true
