language: csharp
solution: src/VcEngineAutomation.sln

env:
  global:
    - PKG_VERSION=0.3.2

install:
  - curl -Lsfo build.sh https://raw.githubusercontent.com/cake-build/example/master/build.sh

before_script:
  - chmod a+x build.sh

script:
  - ./build.sh build.cake -target ZipPack

deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - ./build.sh -target NugetPush
    on:
      tags: true

  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: output/VcEngineRunner.$PKG_VERSION.zip
    on:
      tags: true
