language: csharp
solution: src/VcEngineAutomation.sln

script:
  - xbuild /p:Configuration=Release src/VcEngineAutomation.sln
  - nuget.exe pack ./nuspec/VcEngineAutomation.nuspec -Version $MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
